/* This file was automatically generated.  Do not edit! */
VOID cvtsi2sd_m64_2xmm(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID cvtsi2sd_m32_2xmm(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID cvtsi2sd_r2xmm(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID handle_pcmpistri_m(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID handle_pcmpistri_xmm(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID bswap(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 reg_width,UINT32 opcode);
VOID handle_vzeroupper(thread_ctx_t *thread_ctx,UINT32 opcode);
VOID handle_syscall(thread_ctx_t *thread_ctx,UINT32 opcode);
VOID shiftr_pdq_ymm_imm_bytes_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID shiftl_pdq_ymm_imm_bytes_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID shiftr_pq_ymm_m_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,ADDRINT count_addr,UINT32 opcode);
VOID shiftr_pq_ymm_ymm_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftr_pq_ymm_imm_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID shiftl_pq_ymm_m_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,ADDRINT count_addr,UINT32 opcode);
VOID shiftl_pq_ymm_ymm_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftl_pq_ymm_imm_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID shiftr_pd_ymm_m_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,ADDRINT count_addr,UINT32 opcode);
VOID shiftr_pd_ymm_ymm_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftr_pd_ymm_imm_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID shiftl_pd_ymm_m_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,ADDRINT count_addr,UINT32 opcode);
VOID shiftl_pd_ymm_ymm_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftl_pd_ymm_imm_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID shiftr_pw_ymm_m_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,ADDRINT count_addr,UINT32 opcode);
VOID shiftr_pw_ymm_ymm_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftr_pw_ymm_imm_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID shiftl_pw_ymm_m_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,ADDRINT count_addr,UINT32 opcode);
VOID shiftl_pw_ymm_ymm_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftl_pw_ymm_imm_bits_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID ymm2r_xfer_op32_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID ymm_m2ymm_src_union_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src1,UINT32 src2,UINT32 opcode);
VOID ymm_ymm2ymm_src_union_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src1,UINT32 src2,UINT32 opcode);
VOID ymm2m_union_2op256(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
VOID m2ymm_union_2op256(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID ymm2ymm_union_2op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID ymm2m_xfer_2op256(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
VOID m2ymm_xfer_2op256(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID ymm2ymm_xfer_2op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID pinsrd_m_2op128(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT64 index,UINT32 opcode);
VOID pinsrd_r_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 index,UINT32 opcode);
void pmulqdq_m_2op128(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 index,UINT32 opcode);
void pmulqdq_xmm_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 index,UINT32 opcode);
VOID shuf_dw_xmm_xmm_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 order,UINT32 opcode);
VOID shuf_dw_xmm_xmm_3op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 order,UINT32 opcode);
VOID shuf_b_xmm_xmm_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src1,UINT32 src2,UINT32 src2_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shuf_b_xmm_xmm_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 src_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID interleave_low_w_xmm_m_2op128(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID interleave_low_w_xmm_xmm_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID interleave_low_b_xmm_m_2op128(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID interleave_low_b_xmm_xmm_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID shiftr_pq_xmm_m_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,ADDRINT count_addr,UINT32 opcode);
VOID shiftr_pq_xmm_xmm_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftr_pq_xmm_imm_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID shiftl_pq_xmm_m_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,ADDRINT count_addr,UINT32 opcode);
VOID shiftl_pq_xmm_xmm_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftl_pq_xmm_imm_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID shiftr_pd_xmm_m_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,ADDRINT count_addr,UINT32 opcode);
VOID shiftr_pd_xmm_xmm_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftr_pd_xmm_imm_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID shiftl_pd_xmm_m_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,ADDRINT count_addr,UINT32 opcode);
VOID shiftl_pd_xmm_xmm_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftl_pd_xmm_imm_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID shiftr_pw_xmm_m_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,ADDRINT count_addr,UINT32 opcode);
VOID shiftr_pw_xmm_xmm_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftr_pw_xmm_imm_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID shiftl_pw_xmm_m_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,ADDRINT count_addr,UINT32 opcode);
VOID shiftl_pw_xmm_xmm_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftl_pw_xmm_imm_bits_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID shiftr_pq_xmm_m_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT count_addr,UINT32 opcode);
VOID shiftr_pq_xmm_xmm_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftr_pq_xmm_imm_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftl_pq_xmm_m_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT count_addr,UINT32 opcode);
VOID shiftl_pq_xmm_xmm_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftl_pq_xmm_imm_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftr_pd_xmm_m_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT count_addr,UINT32 opcode);
VOID shiftr_pd_xmm_xmm_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftr_pd_xmm_imm_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftl_pd_xmm_m_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT count_addr,UINT32 opcode);
VOID shiftl_pd_xmm_xmm_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftl_pd_xmm_imm_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftr_pw_xmm_m_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT count_addr,UINT32 opcode);
VOID shiftr_pw_xmm_xmm_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftr_pw_xmm_imm_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftl_pw_xmm_m_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT count_addr,UINT32 opcode);
VOID shiftl_pw_xmm_xmm_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 count_reg,CONTEXT *pin_ctx,UINT32 opcode);
VOID shiftl_pw_xmm_imm_bits_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftr_pdq_xmm_imm_bytes_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID shiftl_pdq_xmm_imm_bytes_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID shiftr_xmm_imm_bytes_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftl_xmm_imm_bytes_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID xmm2r_xfer_op16_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID xmm2m_xfer_2op64(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
VOID m2xmm_xfer_2op64_zx256(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID m2xmm_xfer_2op64_zx128(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID xmm2r_xfer_2op64(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID r2xmm_xfer_2op64_zx256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID r2xmm_xfer_2op64_zx128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID xmm2m_xfer_2op32(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
VOID m2xmm_xfer_2op32_zx256(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID m2xmm_xfer_2op32_zx128(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID xmm2r_xfer_2op32(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID r2xmm_xfer_2op32_zx256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID r2xmm_xfer_2op32_zx128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID xmm_h2m64_xfer_2op128_h(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID xmm_l2m64_xfer_2op128_l(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID m64_xmm_l2xmm_xfer_2op128_h(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src1,ADDRINT src2,UINT32 opcode);
VOID m64_xmm_h2xmm_xfer_2op128_l(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src1,ADDRINT src2,UINT32 opcode);
VOID m64_2xmm_h_xfer_2op128_h(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID m64_2xmm_l_xfer_2op128_l(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID xmm_m2xmm_src_union_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src1,ADDRINT src2,UINT32 opcode);
VOID xmm_xmm2xmm_src_union_3op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src1,UINT32 src2,UINT32 opcode);
VOID xmm2m_union_2op128(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
VOID m2xmm_union_2op128(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID xmm2xmm_union_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID xmm2m_xfer_2op128(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
VOID m2xmm_xfer_2op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID m2xmm_xfer_2op128(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID xmm2xmm_xfer_2op128_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID xmm2xmm_xfer_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID alignr_ymm_m_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src1,ADDRINT src2,UINT64 count,UINT32 opcode);
VOID alignr_ymm_ymm_3op256(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src1,UINT32 src2,UINT64 count,UINT32 opcode);
VOID alignr_xmm_m_3op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src1,ADDRINT src2,UINT64 count,UINT32 opcode);
VOID alignr_xmm_xmm_3op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src1,UINT32 src2,UINT64 count,UINT32 opcode);
VOID alignr_m_2op128(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT64 count,UINT32 opcode);
VOID alignr_xmm_2op128(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count,UINT32 opcode);
VOID rotatel_m_bits_2op8(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 count_is_reg,UINT32 opcode);
VOID rotatel_m_bits_2op16(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 count_is_reg,UINT32 opcode);
VOID rotatel_m_bits_2op32(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 count_is_reg,UINT32 opcode);
VOID rotatel_m_bits_2op64(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 count_is_reg,UINT32 opcode);
VOID rotatel_r_bits_2op8u(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 count_is_reg,UINT32 opcode);
VOID rotatel_r_bits_2op8l(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 count_is_reg,UINT32 opcode);
VOID rotatel_r_bits_2op16(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 count_is_reg,UINT32 opcode);
VOID rotatel_r_bits_2op32(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 count_is_reg,UINT32 opcode);
VOID rotatel_r_bits_2op64(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 count_is_reg,UINT32 opcode);
VOID mm2r_xfer_op8_zero_upper(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID mm2r_xfer_2op64(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID r2mm_xfer_2op64(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID mm2m_xfer_2op32(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
VOID m2mm_xfer_2op32_zx64(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID mm2r_xfer_2op32(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID r2mm_xfer_2op32_zx64(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID mm2m_union_2op64(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
VOID m2mm_union_2op64(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID mm2mm_union_2op64(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID mm2m_xfer_2op64(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
VOID m2mm_xfer_2op64(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
VOID mm2mm_xfer_2op64(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
VOID unhandled_mem_read(VOID *addr,UINT32 num,UINT32 opcode);
VOID shiftr_in_mr_bits_3op16(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT64 count_arg,UINT32 reg_width,UINT32 opcode);
VOID shiftr_in_mr_bits_3op32(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT64 count_arg,UINT32 reg_width,UINT32 opcode);
VOID shiftr_in_mr_bits_3op64(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT64 count_arg,UINT32 reg_width,UINT32 opcode);
VOID shiftr_in_rr_bits_3op16(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count_arg,UINT32 reg_width,UINT32 opcode);
VOID shiftr_in_rr_bits_3op32(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count_arg,UINT32 reg_width,UINT32 opcode);
VOID shiftr_in_rr_bits_3op64(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count_arg,UINT32 reg_width,UINT32 opcode);
VOID shiftl_in_mr_bits_3op16(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT64 count_arg,UINT32 reg_width,UINT32 opcode);
VOID shiftl_in_mr_bits_3op32(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT64 count_arg,UINT32 reg_width,UINT32 opcode);
VOID shiftl_in_mr_bits_3op64(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT64 count_arg,UINT32 reg_width,UINT32 opcode);
VOID shiftl_in_rr_bits_3op16(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count_arg,UINT32 reg_width,UINT32 opcode);
VOID shiftl_in_rr_bits_3op32(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count_arg,UINT32 reg_width,UINT32 opcode);
VOID shiftl_in_rr_bits_3op64(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT64 count_arg,UINT32 reg_width,UINT32 opcode);
VOID shiftr_m_bits_2op8(thread_ctx_t *thread_ctx,ADDRINT dst,UINT64 count,UINT32 opcode);
VOID shiftr_m_bits_2op16(thread_ctx_t *thread_ctx,ADDRINT dst,UINT64 count,UINT32 opcode);
VOID shiftr_m_bits_2op32(thread_ctx_t *thread_ctx,ADDRINT dst,UINT64 count,UINT32 opcode);
VOID shiftr_m_bits_2op64(thread_ctx_t *thread_ctx,ADDRINT dst,UINT64 count,UINT32 opcode);
VOID shiftr_r_bits_2op8u(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftr_r_bits_2op8l(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftr_r_bits_2op16(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftr_r_bits_2op32(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftr_r_bits_2op64(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftl_m_bits_2op8(thread_ctx_t *thread_ctx,ADDRINT dst,UINT64 count,UINT32 opcode);
VOID shiftl_m_bits_2op16(thread_ctx_t *thread_ctx,ADDRINT dst,UINT64 count,UINT32 opcode);
VOID shiftl_m_bits_2op32(thread_ctx_t *thread_ctx,ADDRINT dst,UINT64 count,UINT32 opcode);
VOID shiftl_m_bits_2op64(thread_ctx_t *thread_ctx,ADDRINT dst,UINT64 count,UINT32 opcode);
VOID shiftl_r_bits_2op8u(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftl_r_bits_2op8l(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftl_r_bits_2op16(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftl_r_bits_2op32(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
VOID shiftl_r_bits_2op64(thread_ctx_t *thread_ctx,UINT32 dst,UINT64 count,UINT32 opcode);
void rm2r_binary_opl(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src1,ADDRINT src2,UINT32 opcode);
void rm2r_binary_opll(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src1,ADDRINT src2,UINT32 opcode);
void rr2r_binary_opl(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src1,UINT32 src2,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2m_save_opl(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2m_save_opw(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_restore_opl(thread_ctx_t *thread_ctx,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_restore_opw(thread_ctx_t *thread_ctx,ADDRINT src,UINT32 opcode);
ADDRINT PIN_FAST_ANALYSIS_CALL rep_predicate(BOOL first_iteration,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2m_xfer_oplln(ADDRINT dst,ADDRINT src,ADDRINT count,ADDRINT eflags,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2m_xfer_opln(ADDRINT dst,ADDRINT src,ADDRINT count,ADDRINT eflags,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2m_xfer_opbn(ADDRINT dst,ADDRINT src,ADDRINT count,ADDRINT eflags,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2m_xfer_opwn(ADDRINT dst,ADDRINT src,ADDRINT count,ADDRINT eflags,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2m_xfer_opll(ADDRINT dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2m_xfer_opl(ADDRINT dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2m_xfer_opb(ADDRINT dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2m_xfer_opw(ADDRINT dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2m_xfer_opl(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2m_xfer_opll(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2m_xfer_opw(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2m_xfer_opb_l(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2m_xfer_opb_u(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2m_xfer_opbn(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 count,UINT32 eflags,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_xfer_opll(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_xfer_opl(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_xfer_opw(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_xfer_opb_l(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_xfer_opb_u(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_xfer_opl(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_xfer_opw(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_xfer_opb_l(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_xfer_opb_u(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_xfer_opb_lu(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_xfer_opb_ul(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r_clrb_l(thread_ctx_t *thread_ctx,UINT32 reg,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r_clrb_u(thread_ctx_t *thread_ctx,UINT32 reg,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r_clrw(thread_ctx_t *thread_ctx,UINT32 reg,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r_clrl(thread_ctx_t *thread_ctx,UINT32 reg,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r_clrl2(thread_ctx_t *thread_ctx,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r_clrl4(thread_ctx_t *thread_ctx,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2m_binary_opll(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2m_binary_opl(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2m_binary_opw(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2m_binary_opb_l(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2m_binary_opb_u(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_binary_opll(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_binary_opl(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_binary_opw(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_binary_opb_l(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_binary_opb_u(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_binary_opl(thread_ctx_t *thread_ctx,ADDRINT dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_binary_opw(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_binary_opb_l(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_binary_opb_u(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_binary_opb_lu(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_binary_opb_ul(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_div_opll(thread_ctx_t *thread_ctx,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_div_opl(thread_ctx_t *thread_ctx,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_div_opw(thread_ctx_t *thread_ctx,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_div_opb(thread_ctx_t *thread_ctx,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_div_opl(thread_ctx_t *thread_ctx,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_div_opw(thread_ctx_t *thread_ctx,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_div_opb_l(thread_ctx_t *thread_ctx,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_div_opb_u(thread_ctx_t *thread_ctx,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_mul_opll(thread_ctx_t *thread_ctx,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_mul_opl(thread_ctx_t *thread_ctx,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_mul_opw(thread_ctx_t *thread_ctx,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL m2r_mul_opb(thread_ctx_t *thread_ctx,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_mul_opl(thread_ctx_t *thread_ctx,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_mul_opw(thread_ctx_t *thread_ctx,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_mul_opb_l(thread_ctx_t *thread_ctx,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL r2r_mul_opb_u(thread_ctx_t *thread_ctx,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _lea_r2r_opl(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 base,UINT32 index,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _lea_r2r_opw(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 base,UINT32 index,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _xadd_r2m_opb_l(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _xadd_r2m_opb_u(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _xadd_r2m_opw(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _xadd_r2m_opl(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _xadd_r2m_opll(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _xchg_r2m_opb_l(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _xchg_r2m_opb_u(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _xchg_r2m_opw(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _xchg_r2m_opl(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _xchg_r2m_opll(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL cmpxchg16_r2m_eq(thread_ctx_t *thread_ctx,ADDRINT dst,ADDRINT src1_val,ADDRINT src2_val,UINT32 opcode);
ADDRINT PIN_FAST_ANALYSIS_CALL cmpxchg16_r2m_neq(thread_ctx_t *thread_ctx,ADDRINT dst,ADDRINT src1_val,ADDRINT src2_val,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL cmpxchg8_r2m_eq(thread_ctx_t *thread_ctx,ADDRINT dst,ADDRINT src1_val,ADDRINT src2_val,UINT32 opcode);
ADDRINT PIN_FAST_ANALYSIS_CALL cmpxchg8_r2m_neq(thread_ctx_t *thread_ctx,ADDRINT dst,ADDRINT src1_val,ADDRINT src2_val,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _cmpxchg_r2m_opw_slow(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
ADDRINT PIN_FAST_ANALYSIS_CALL _cmpxchg_m2r_opw_fast(thread_ctx_t *thread_ctx,ADDRINT dst_val,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _cmpxchg_r2m_opl_slow(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
ADDRINT PIN_FAST_ANALYSIS_CALL _cmpxchg_m2r_opl_fast(thread_ctx_t *thread_ctx,ADDRINT dst_val,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _cmpxchg_r2m_opll_slow(thread_ctx_t *thread_ctx,ADDRINT dst,UINT32 src,UINT32 opcode);
ADDRINT PIN_FAST_ANALYSIS_CALL _cmpxchg_m2r_opll_fast(thread_ctx_t *thread_ctx,ADDRINT dst_val,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _cmpxchg_r2r_opw_slow(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
ADDRINT PIN_FAST_ANALYSIS_CALL _cmpxchg_r2r_opw_fast(thread_ctx_t *thread_ctx,ADDRINT dst_val,UINT32 src,UINT32 src_val,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL _cmpxchg_r2r_opl_slow(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
ADDRINT PIN_FAST_ANALYSIS_CALL _cmpxchg_r2r_opl_fast(thread_ctx_t *thread_ctx,ADDRINT dst_val,UINT32 src,ADDRINT src_val,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL zx_m2r_opllw(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL zx_m2r_opllb(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL zx_m2r_oplw(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL zx_m2r_oplb(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL zx_m2r_opwb(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL zx_r2r_oplb_l(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL zx_r2r_oplb_u(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL zx_r2r_oplw(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL zx_r2r_opllb_l(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL zx_r2r_opllb_u(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL zx_r2r_opwb_l(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL zx_r2r_opwb_u(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL sx_m2r_opllw(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL sx_m2r_oplll(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL sx_m2r_opllb(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL sx_m2r_oplw(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL sx_m2r_oplb(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL sx_m2r_opwb(thread_ctx_t *thread_ctx,UINT32 dst,ADDRINT src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL sx_r2r_oplll(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL sx_r2r_oplw(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL sx_r2r_oplb_l(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL sx_r2r_oplb_u(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL sx_r2r_opllw(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL sx_r2r_opllb_l(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL sx_r2r_opllb_u(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL sx_r2r_opwb_l(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void PIN_FAST_ANALYSIS_CALL sx_r2r_opwb_u(thread_ctx_t *thread_ctx,UINT32 dst,UINT32 src,UINT32 opcode);
void m2r_32(thread_ctx_t *thread_ctx,UINT32 dst_reg,ADDRINT src);
extern REG thread_ctx_ptr;
